<div class="row justify-content-md-center main-div" id="buttons">
    <div class="row">
        <button type="button" class="btn btn-info editing-btns" id="addthat">Add</button>
        <button type="submit" class="btn btn-info editing-btns" id="edit">Edit</button>
        <button type="submit" class="btn btn-info" id="del">Delete</button>
        <button type="submit" class="btn btn-info conf-btns" id="confirm">Confirm</button>
        <button type="submit" class="btn btn-warning conf-btns" id="test">Test Load Db</button>

    </div>
</div>